pipeline{

	agent any

	environment {
		DOCKERHUB_CREDENTIALS=credentials('dockerhub')
	}

	stages {

		stage('Build') {

			steps {
			    dir("./frontend") {
                    sh 'echo "REACT_APP_API_URL=http://3.35.170.113:31738" > .env'
			        sh 'npm i'
                    sh 'npm run build'
                    sh 'docker build -t gkuer/joalarm-react .'
			    }
			}
		}

		stage('Login') {

			steps {
				sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
			}
		}

		stage('Push') {

			steps {
				sh 'docker push gkuer/joalarm-react'
			}
		}
	}

	post {
		always {
			sh 'docker logout'
		}
	}

}