pipeline{

	agent any

	environment {
		DOCKERHUB_CREDENTIALS=credentials('dockerhub')
	}

	stages {

		stage('Build') {

			steps {
			    dir("./frontend") {
			        sh 'npm i'
                    sh 'CI=false npm run build'
                    sh 'docker build -t gkuer/joalarm-react:latest .'
			    }
			}
		}

		stage('Login') {

			steps {
				sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
			}
		}

		stage('Push') {

			steps {
				sh 'docker push gkuer/joalarm-react'
			}
		}
	}

	post {
		always {
			sh 'docker logout'
		}
	}

}