kind: Deployment
apiVersion: apps/v1
metadata:
  name: react
spec:
  replicas: 7
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: react
          image: gkuer/joalarm-react:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
      restartPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  name: service-react
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: react
